### ISSUE TITLE
Problem with context menu bindind with mixin

### ISSUE THREAD

**Issue by m00nlighter** [aratcliffe/Leaflet.contextmenu#113]
with this simple code from readme when u click context menu twice it show 2 copy of menu item added
here is gif
![1](https://user-images.githubusercontent.com/5832582/46947071-5ed2cf80-d082-11e8-8e99-b3e81c8c5190.gif)

```
var jsonLayer = L.geoJson(jsonData, {
	onEachFeature: function (feature, layer) {
        layer.bindContextMenu({
            contextmenu: true,
	        contextmenuItems: [{
	            text: 'Marker item'
	        }]
        });
	}
 }).addTo(map);
```

**Comment by m00nlighter** [comment]
adding context menu, true to map config resolve this problem.

var map = L.map('map', {
    layers: [OpenStreetMap_Mapnik],
    contextmenu: true
});

**Comment by veloper** [comment]
Thank you! @m00nlighter

This solved the issue for me as well.
