### ISSUE TITLE
GeoJSON layer support

### ISSUE THREAD

**Issue by sookoll** [aratcliffe/Leaflet.contextmenu#12]
It would be nice to have also opportunity to add context menu for features come from geojson. Something like:

```
L.geoJson(json,{
  ...
  onEachFeature: function (feature, layer) {
    layer.contextmenu = true;
    layer.contextmenuItems = [
      ...
    ];
});
```

**Comment by Puyou** [comment]
Thats great for markers, but how can you do the same in a polygon from GEOJSON?

**Comment by aratcliffe** [comment]
Use http://leafletjs.com/reference-1.0.3.html#geojson-oneachfeature and the context menu mixin's bindContextMenu method.

**Comment by Puyou** [comment]
That's exactly what Im doing, and it shows the contextMenu over the polygon, but it also shows "below" the original contextmenu of the map, and when I "use" or "click" on the polygon contextmenu, the map "below" it does not hide.
I dont know if Im doing something wrong:

var nL = L.geoJson(feat, {
                        style: stylePoligonos,
                        onEachFeature: function (feature, layer) {
                            layer.bindContextMenu({
                                contextmenu: true,
                                contextmenuInheritItems: false,
                                contextmenuItems: [ {
                                        text: 'Polygon marker item' }]
                            });
                         }
                    });

**Comment by aratcliffe** [comment]
Can you provide a full test case I can work with? Also what version of Leaflet are you using and does this problem effect all browsers?

**Comment by Puyou** [comment]
You can run the example, I just added the polygon. You can see that you will have the menu OVER the polygon, but once you click on it, the "map menu" will still be there on the back. If you chance to false the contextmenuInheritItems, you will see that the item of the polygon will appear OVER the "map menu". I tested it on chrome and explorer and it does the same:
-----------------

<!doctype html>
<html>
  <head>
    <title>Leaflet Context Menu</title>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.1/dist/leaflet.css"/>
    <link rel="stylesheet" href="../dist/leaflet.contextmenu.css"/>
  </head>
  <body>
    <div id="map" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></div>
    <script src="https://unpkg.com/leaflet@1.0.1/dist/leaflet.js"></script>
    <script src="../dist/leaflet.contextmenu.js"></script>
    <script src="../src/Map.ContextMenu.js"></script>
    <script>
      var map,
          cm,
          ll = new L.LatLng(-36.852668, 174.762675),
          ll2 = new L.LatLng(-36.86, 174.77);

      function showCoordinates (e) {
	      alert(e.latlng);
      }

      function centerMap (e) {
	      map.panTo(e.latlng);
      }

      function zoomIn (e) {
	      map.zoomIn();
      }

      function zoomOut (e) {
	      map.zoomOut();
      }

      map = L.map('map', {
	      center: ll,
	      zoom: 15,
	      contextmenu: true,
          contextmenuWidth: 140,
	      contextmenuItems: [{
		      text: 'Show coordinates',
		      callback: showCoordinates
	      }, {
		      text: 'Center map here',
		      callback: centerMap
	      }, '-', {
		      text: 'Zoom in',
		      icon: 'images/zoom-in.png',
		      callback: zoomIn
	      }, {
		      text: 'Zoom out',
		      icon: 'images/zoom-out.png',
		      callback: zoomOut
	      }]     
      });

	  L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
		  attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
	  }).addTo(map);

      L.marker(ll, {
          contextmenu: true,
          contextmenuItems: [{
              text: 'Marker item',
              index: 0
          }, {
              separator: true,
              index: 1
          }]
      }).addTo(map);

      L.marker(ll2, {
          contextmenu: true,
          contextmenuInheritItems: false,
          contextmenuItems: [{
              text: 'Marker item'
          }]
      }).addTo(map);

      var polygon = L.polygon([
        [-36.78271, 174.67091],
        [-36.89152, 174.64207],
        [-36.91074, 174.82815]
      ]).addTo(map);

      polygon.bindContextMenu({
          contextmenu: true,
          contextmenuInheritItems: true,
          contextmenuItems: [{
              text: 'Polygon marker item'
          }]
      });


    </script>
  </body>
</html>

--------------------------
THANK YOU VERY MUCH

**Comment by aratcliffe** [comment]
The issue is that the example was checked in with the context menu source code included `<script src="../src/Map.ContextMenu.js"></script>`. This has the effect of initialising 2 context menu instances when there should only be one. If you add your polygon to the fixed example I've just checked in you will get the correct behaviour.

**Comment by Puyou** [comment]
Great!
That was it!
THANKS AGAIN!
