### ISSUE TITLE
BindContextMenu pasar parametros en el callback

### ISSUE THREAD

**Issue by emilgonz1959** [aratcliffe/Leaflet.contextmenu#139]
Dear, I found this tool and it is fabulous for the work that I am doing.
I am an amateur and sometimes I consult things that must be very simple, if so I apologize from now on.
I am using bindContextMenu in an onEachFeature with Leaflet.
In the callback I call a JS function and my question is: Is it possible to pass parameters when this function is called?

The code is:

var camino = (feature.properties['NumProyect'] !== null ? autolinker.link(feature.properties['NumProyect'].toLocaleString()) : '');                                         
                    layer.bindContextMenu({ 
                        contextmenu : true , 
                        contextmenuItems : [ { 
                         text : 'Ingresar trabajos en el cno. No:'+ '  ' + camino,                         
                         callback : ingresomant 
                            } ] 
                        });

and what I want is that when calling the ingresomant function in the callback pass it the variable path.

something like that (clearly this is wrong)

 function ingresomant (e) {            
        location.href ="mantenimientorural.php?camino=" + camino;
        }

From already thank you very much!!

**Comment by aratcliffe** [comment]
If you define your callback function for each context menu item inline as an anonymous function the feature argument that's passed on each call to onEachFeature will be in scope and you can access its properties in your callback function. For example:

````
contextmenuItems: [{
                text : 'Ingresar trabajos en el cno. No:'+ ' ' + camino,
                callback: function (e) {
                   var camino = (feature.properties['NumProyect'] !== null ? autolinker.link(feature.properties['NumProyect'].toLocaleString()) : '')
                }
            }]
````

**Comment by emilgonz1959** [comment]
Thank you so much for your help!!
