### ISSUE TITLE
Adding Menus to existing layers

### ISSUE THREAD

**Issue by schmijos** [aratcliffe/Leaflet.contextmenu#22]
Is it possible to add a context menu to an already existing layer?

While the following is possible for the map its not working with layers like polyline (there failing at L.Map.ContextMenu.L.Handler.extend._createItems [line 177](https://github.com/aratcliffe/Leaflet.contextmenu/blob/master/src/Map.ContextMenu.js#L177)).

    mapMenu = new L.Map.ContextMenu(map)
    mapMenu.addItem { text: 'Neues Feld', callback: () -> alert('Feld erstellen...') }
    mapMenu.addHooks()

For polylines I'm doing the following which works:

    polygon.options.contextmenu = true
    polygon.options.contextmenuItems = [{ text: "gach", callback: () -> alert("gach") }]
    polygon._initContextMenu()

Is that the only way to add and enable a context menu on something other than a map? It shouldn't be.

**Comment by aratcliffe** [comment]
Sorry for the late reply on this issue. A context menu can be added to all vector layers that extend L.Path declaratively using the layer options. For example:

```javascript
      var polygon = L.polygon([
          [-36.78271, 174.67091],
          [-36.89152, 174.64207],
          [-36.91074, 174.82815]
      ], {
          contextmenu: true,
          contextmenuInheritItems: true,
          contextmenuItems: [{
              text: 'Polygon marker item'
          }]          
      }).addTo(map);      
```

Alternatively it can be added to an existing layer using the bindContextMenu() method:

```javascript
      var polygon = L.polygon([
          [-36.78271, 174.67091],
          [-36.89152, 174.64207],
          [-36.91074, 174.82815]
      ]).addTo(map);

     polygon.bindContextMenu({
          contextmenu: true,
          contextmenuInheritItems: true,
          contextmenuItems: [{
              text: 'Polygon marker item'
          }]          
      });
```

A context menu can also be removed using the unbindContextMenuItem() method.

**Comment by tibiOlteanu** [comment]
Hi,
I have a project where there is a need to show the context menu on map. I use tombatossals/angular-leaflet-directive. It's possible to use this plugin? If yes, could you, please provide an example?
Thank you!

**Comment by aratcliffe** [comment]
Sorry I have no experience with angular so I can't provide you with specifics. Providing you can get a reference to the Leaflet map instance that angular creates I don't see any reason why you can't use this plugin.

**Comment by franleplant** [comment]
:+1:  for `bindContextMenu` syntax! It should be on the docs!

**Comment by franleplant** [comment]
@aratcliffe using the `bindContextMenu` syntax, when the context menu is open and I click in any other area of my viewport, it doesnt close automatically, any ideas?

**Comment by franleplant** [comment]
I solve it by adding to the map creation `contextmenu: true` with no items.

**Comment by aratcliffe** [comment]
@franleplant bindContextMenu() is in the docs.

**Comment by franleplant** [comment]
Yeap, it is, I saw it, but perhaps the full example could put it into
context and show what is it for. Thank you very much for your work :smile:
