### ISSUE TITLE
publish to npm 

### ISSUE THREAD

**Issue by w8r** [aratcliffe/Leaflet.contextmenu#26]
Please, consider publishing your plugin to npm by addign a UMD header and `package.json`. If you are too busy at the moment, I can create a PR with these changes

**Comment by aratcliffe** [comment]
I'm not familiar with packaging client-side javascript for npm but if you want to submit a PR for this I would be happy to merge it :)

**Comment by w8r** [comment]
did that, please review

**Comment by w8r** [comment]
Thank you! but did you publish it on npm? It's has to be done by you so that the package would be linked to your repository

**Comment by aratcliffe** [comment]
Now published on npm :)
