### ISSUE TITLE
Ignore context menus on controls

### ISSUE THREAD

**Issue by netsgnut** [aratcliffe/Leaflet.contextmenu#29]
Recently I am on a project where there is a need to show the context menu on map, however when clicking on a control (L.Control) there should display no menu. Are there any suggested ways to achieve that? Thanks!

**Comment by aratcliffe** [comment]
If I understand correctly you're saying that if a context menu is open on the map and the user clicks on a map control, such as the zoom control, the context menu should be hidden? If so the context menu already works that way. See the example http://aratcliffe.github.io/Leaflet.contextmenu/examples/index.html.  Right click on the map to display the context menu then click on the zoom control.  The context menu will be hidden.
Get back to me if I've misunderstood your question.

**Comment by netsgnut** [comment]
Hmm, looking back on my original issue I do think it is not phrased correctly - sorry for the confusion. Maybe I should try to frame it again.

In my case what the project requires is when right-clicking a control (e.g. zoom control) the context menu should not be triggered.

For example right now we would have something like this:

![201503161149](https://cloud.githubusercontent.com/assets/284779/6660377/91ab5426-cbd2-11e4-85fb-4b9197eebaaa.png)

But ideally the context menu should not be displayed when right-clicking on controls. Instead of that, the browser-specific context menu should be displayed there instead.

![201503161159](https://cloud.githubusercontent.com/assets/284779/6660441/ffc3efee-cbd3-11e4-8578-b086782f5ffc.png)

I am not sure how to achieve that, though, since the plugin now stops the event from bubbling at the base object, which has already stopped before it gets to any of the components. https://github.com/aratcliffe/Leaflet.contextmenu/blob/master/src/Map.ContextMenu.js#L33

Any ideas?

**Comment by aratcliffe** [comment]
Hi, do your users have a need to access the browser context menu for the map controls? If not I wouldn't worry about it. If you do have a requirement to not show the context menu over the map controls I would probably look at registering a contextmenu event handler on each map control that stops the event from propagating to the map and triggering the contextmenu handler registered on the map. This still won't get you the browser context menu for the controls but at least it will stop the app-specific context menu from being shown.

**Comment by netsgnut** [comment]
In my case here my users actually prefers to display the default browser ones. I do understand that if we have to avoid the context menu for controls we probably have to stop it from propagating in individual controls.

That said, judging from what I understand from the current Leaflet.contextmenu implementation, I probably have to hack on how the hooks are added in `addHooks` and `removeHooks`. Specifically in my case the contextmenu event should be on tilePane instead of the map container.

**Comment by aratcliffe** [comment]
Yes specifically you could use the tile container's `contextmenu` event instead of the map's. Looking at the `addHooks()` implementation I think the other map events that are bound to the menu's `_hide()` method could stay as they are. Let me know how it works for you.

**Comment by netsgnut** [comment]
Thanks for your reply. I have finally made a dirty hack on that.

What I did is to change the `addHooks` part to something as:

```js
addHooks: function () {
  L.DomEvent
    .on(document, (L.Browser.touch ? this._touchstart : 'mousedown'), this._onMouseDown, this)
    .on(document, 'keydown', this._onKeyDown, this);

  this._map.on({
    mouseout: this._hide,
    mousedown: this._hide,
    movestart: this._hide,
    zoomstart: this._hide
  }, this);

  if (this._map.options.contextmenuIgnoreControls && this._map.getPanes()['overlayPane']) {
    var self = this;
    L.DomEvent.on(self._map.getPanes()['overlayPane'], 'contextmenu', function _showOnOverlay (e) {
      e.preventDefault();
      e.containerPoint = self._map.mouseEventToContainerPoint(e);
      self._show(e);
    }, this);
  } else {
    this._map.on({
      contextmenu: this._show
    }, this);
  }
 }
```

I admit this is a dirty hack. And we are to do it properly I will at least have to rewrap the lambda function as instance method. I can do it that way and submit a PR if you like to support future requests like what I do here as well. Do you want a PR on that?

**Comment by adriennn** [comment]
@netsgnut have you done a pull request yet? I'm having the same issue as you excepted this one is more annoying: the context menu fires up on map controls such as the lealfet.sidebar.

**Comment by netsgnut** [comment]
Thanks for the reminder: eventually what I did was simply scrapping away the contextMenu concept as a whole here due to requirement change, but shouldn't really take long if you want a crude PR in. I think the only step that we miss here is to remove the hooks accordingly, but we probably need to test more on other plugins' compatibility - my mod here is a horrible hack, after all.

@adriennn May I ask which plugins did you use? (And I guess you are on the Leaflet 0.7.3 as well instead of 1.0.0-alpha?) In my project I also used a sidebar plugin too ([this one to be exact](https://github.com/turbo87/leaflet-sidebar/)) but never had any problem? Would you mind elaborating a bit more as well?

**Comment by adriennn** [comment]
@netsgnut  I'm on leaflet 0.7.3 and the sidebar by Turbo87 as well. I might scrap the context menu as it is not a strict requirement for my project either. What I meant is that if I right click on an open sidebar pane, the context menu will be displayed on top of the sidebar and - in my case - add a marker or do something else on the map below.

**Comment by netsgnut** [comment]
@adriennn Are you using the [original one](https://github.com/turbo87/leaflet-sidebar/) or the [tabbed sibling](https://github.com/Turbo87/sidebar-v2)? I remember that I had some trouble on the tabbed variant which eventually I decided to rollback to the original one.

Regarding your problem, sadly it seems I have not really faced it back then. However, one note is that what my hack is actually doing is to, instead of letting Leaflet.contextmenu to bind directly to the base `map` object, it binds the contextmenu onto the overlay pane instead.

```js
var self = this;
L.DomEvent.on(self._map.getPanes()['overlayPane'], 'contextmenu', function _showOnOverlay (e) {
  e.preventDefault();
  e.containerPoint = self._map.mouseEventToContainerPoint(e);
  self._show(e);
}, this);
```

Just an uneducated guess - but maybe you can try to see if there are code that bubbles the events on the sidebar to the overlay pane, thus rendering the context menu?

**Comment by adriennn** [comment]
I used the original, but as I have an issue with another leaflet plugin as well, I'm thinking of holding on a little to see how leaflet1.0 fares or switching to ol3.  thanks for your code though.

**Comment by netsgnut** [comment]
I am evaluating Leaflet 1.0 here as well: the API seems to be changing quite a lot and really needs rework on many of the plugins. Thanks for reminding on the OpenLayers option, too.

**Comment by aratcliffe** [comment]
@netsgnut have you tried this plugin with Leaflet 1.0? I haven't looked at it yet but will update soon when I have a little more time.

**Comment by netsgnut** [comment]
@aratcliffe Oops sorry that I haven't noticed this issue back then. I am trying to move over to Leaflet 1.0, but it seems it breaks quite some plugins... :(

**Comment by aratcliffe** [comment]
@netsgnut There was a problem with the context menu hiding when moving the mouse after opening the menu. This was due to the map's mouseout event behaviour changing in Leaflet 1.0. I've now resolved this problem and the plugin is compatible with 1.0.

**Comment by netsgnut** [comment]
@aratcliffe I see. Thanks for the update! I will also keep that in mind while I move other plugins to 1.0.
