### ISSUE TITLE
Help please, run ajax from context menu

### ISSUE THREAD

**Issue by AlexSpain** [aratcliffe/Leaflet.contextmenu#30]
Hello,

function runAjax (id) {
 console.log(id);
}

callback: runAjax (id)

So then we reload page, it every time run all callback from all markers.

Thank you.

**Comment by aratcliffe** [comment]
Hi, when you define a context menu item you specify a callback to be run when that menu item is clicked. The callback will be passed a single argument, a Leaflet [MouseEvent](http://leafletjs.com/reference.html#mouse-event). Take a look at the demo code. If that's still not clear you could post the full code you're using to create the context menu.

**Comment by AlexSpain** [comment]
var LamMarker = new L.marker([items[i][0], items[i][1]],{contextmenu: true, contextmenuInheritItems: false, contextmenuWidth: 140, contextmenuItems: [{
              text: items[i][2],
              index: 0
          }, {
              separator: true,
              index: 1
          },{
		      text: 'items[i][2]',
			callback: showCoordinates(items[i][2])
	      }], icon: iconT, title: items[i][2]}).bindPopup(''+items[i][3]+':'+items[i][2]+'');
		lgrup.addLayer(LamMarker);

**Comment by aratcliffe** [comment]
The callback needs to be a reference to a function that will be called when the user clicks on the menu item. You're invoking the function at the time when you create the marker, that's why it's run for each of your markers when you reload the page. Have a look at the example code if you're unsure what your code should look like.

**Comment by AlexSpain** [comment]
Dear aratcliffe, Can you help me please send vars from your contextmenu to function? And how I can reffer to marker from function? I cant find examples with this options.
Thank you.

**Comment by aratcliffe** [comment]
You need to listen to the `contextmenu.show` on the map. It will receive an event object with a `relatedTarget` property that is a reference to the marker the context menu was opened on. This is described in more details in the docs.

**Comment by AlexSpain** [comment]
Dear aratcliffe, please can you give me link to this docs? I can't find reference to marker. Very appreciate your help. Thank you.

**Comment by aratcliffe** [comment]
Look at the events section of the docs: https://github.com/aratcliffe/Leaflet.contextmenu
