### ISSUE TITLE
Submenu suport

### ISSUE THREAD

**Issue by srdjank** [aratcliffe/Leaflet.contextmenu#31]
Is there any way/suggestion how to dinamicly add submenu items?

**Comment by aratcliffe** [comment]
The plugin was designed to be simple and lightweight and would probably require a re-write to support hierarchical menus. Depending upon what you're trying to do you could take a different approach and have a toolbar that acts upon the selected feature?

**Comment by srdjank** [comment]
That is other option that we consider, but importance is to have the menu populated depending on click on diferents polygons or markers.
We will also evaluate option to call some bootstrap context menu.
Thank you for your answer!
