### ISSUE TITLE
Context menu style issue with JQuery Mobile

### ISSUE THREAD

**Issue by kamocio** [aratcliffe/Leaflet.contextmenu#33]
When I include JQuery mobile the styling of conext menu gets weird (low fidelity fonts are used)

All you have to do to repro is to include this script in the head:

http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js

Saw same issue with the older versions of JQuery

**Comment by aratcliffe** [comment]
Hi, sorry but I'm unable to provide support for 3rd party libraries. All of the styles in the context menu stylesheet are scoped to the context menu with the `leaflet-contextmenu` prefix so it sounds like jQuery mobile is using some non-specific styling rules which are affecting the context menu. I'd suggest inspecting the context menu element in your browser and looking at the style inheritance hierarchy, you should be able to see which rule in the jQuery mobile stylesheet is causing the issue.
