### ISSUE TITLE
Doesn´t work over a polygon layer

### ISSUE THREAD

**Issue by geocentrum1** [aratcliffe/Leaflet.contextmenu#34]
When any polygon (GeoJSON) layer is switched on I am not able to open context menu by right-click. Outside a layer or when layer is switched off it works great. Any idea? Thanks

**Comment by aratcliffe** [comment]
Hi, I haven't seen that issue but then again I've never used a geojson layer. Do you have a test case that demonstrates the problem?

**Comment by rostanetek** [comment]
Hi, the example is available on: http://rostanetek.cz/_geocentrum/v6/prikazy/test.html . Over the layer it doesn´t work, while outside it is OK.

**Comment by geocentrum1** [comment]
Hi, the example is available on: http://rostanetek.cz/_geocentrum/v6/prikazy/test.html . Over the layer it doesn´t work, while outside it is OK.

**Comment by aratcliffe** [comment]
I think you'll need to use a combination of the [GeoJSON.onEachFeature()](http://leafletjs.com/reference.html#geojson-oneachfeature) method and the bindContextMenu() method that the plugin mixin adds to the L.Path layer. Can you try that and let me know how it goes?

**Comment by geocentrum1** [comment]
Amazing! It is neccessary only add "contextmenu: true"  into  onEachFeature e.g. "onEachFeature:popUp, contextmenu: true". Thanks

**Comment by aratcliffe** [comment]
Great! Can you share the complete code you're using for the GeoJSON layer so I can look at adding an example to the docs?

**Comment by tibiOlteanu** [comment]
Hi,
I have a problem with polygon (GeoJSON) layer - is it possible to know which polygon was selected in the function deletePolygon,()?

contextmenu: true,
contextmenuItems: [{
	text: 'Delete polygon',
        icon: 'images/delete.png',
        callback: deletePolygon,
        index: 0
}, 
{
	separator: true,
        index: 1
}]

If yes, could you, please provide an example using that type of event?

**Comment by aratcliffe** [comment]
See https://github.com/aratcliffe/Leaflet.contextmenu#contextmenushow.  Add a listener for this map event and the event object's `relatedTarget` property will reference the `L.Path` instance the context menu was opened for.

**Comment by timburgess** [comment]
I'm aware this is a closed issue but striking the same problem with wanting the context menu working on GeoJSON features, the following code worked for me:
<pre>
function onEachFeature(feature, layer) {
          // enable context menu
          layer.on({ contextmenu: true });
 }
</pre>

<i>onEachFeature</i> is well documented at [http://leafletjs.com/reference.html#geojson](http://leafletjs.com/reference.html#geojson)
