### ISSUE TITLE
Example request: how to create a callback to remove the layer clicked

### ISSUE THREAD

**Issue by araichev** [aratcliffe/Leaflet.contextmenu#35]
Could you illustrate in one of your examples how to add a context menu function (callback) to a GeoJSON layer that removes the layer (the one clicked).  I can't figure out how to pass the current layer to the callback function.  Thanks for your attention.

**Comment by aratcliffe** [comment]
Hi Alex, see if this helps: https://github.com/aratcliffe/Leaflet.contextmenu/issues/12
