### ISSUE TITLE
Problem with building on Windows

### ISSUE THREAD

**Issue by aparshin** [aratcliffe/Leaflet.contextmenu#36]
I'm using this plugin in a bigger solution and want to build it automatically as a part of general build process. Unfortunately, our main OS is Windows, and it's not possible to run command `npm run build` from native Windows environment because of missing `cat` command.

Is it possible to write OS independent build script? Maybe `grunt` or `gulp` build systems can be used...

**Comment by aratcliffe** [comment]
Hi, there is already a bower build script. There are instructions for installing bower on windows here: http://m.youtube.com/watch?v=41tpzACUOPo

**Comment by aparshin** [comment]
Bower script references built files in `dist` directory. Do you plan to generate them locally and update with each commit? Can I use these files from the repository without generating them myself?

**Comment by aratcliffe** [comment]
Yes I do update with each commit. I create the .js files using uglifyjs.

**Comment by aparshin** [comment]
Ok, then I will rely on these files in repository. Thanks!
