### ISSUE TITLE
leaflet 1.X compatibility

### ISSUE THREAD

**Issue by SilentT-FR** [aratcliffe/Leaflet.contextmenu#38]
When i use context menu with leaflet 1.0.0.beta1 the context appear, but disappear when i move the mouse

**Comment by SilentT-FR** [comment]
http://codepen.io/anon/pen/NGrKoE

**Comment by aratcliffe** [comment]
I haven't done any compatibility work with Leaflet 1.0 yet. Hope to get onto that soon

**Comment by SilentT-FR** [comment]
I see that
https://github.com/Leaflet/Leaflet/issues/3638

https://github.com/Leaflet/Leaflet/pull/3639

I havent test but i think the bug should come from that

**Comment by erkanarslan** [comment]
I have the same problem

**Comment by SilentT-FR** [comment]
tested with leaflet master at this tree https://github.com/Leaflet/Leaflet/tree/3ff1b65b6453cb859f358a96f4034e0afff62ccd

http://codepen.io/anon/pen/qOaYao

the context menu don't disapear 

all is ok

**Comment by aratcliffe** [comment]
@SilentT-FR  I've updated the plugin to be compatible with Leaflet 1.0 beta 1.  Let me know if you find any further problems.

**Comment by SilentT-FR** [comment]
http://codepen.io/anon/pen/qOaYao same problem

**Comment by aratcliffe** [comment]
Sorry. I forgot to rebuild the dist files. Should be all good now.

**Comment by SilentT-FR** [comment]
perfect

**Comment by SilentT-FR** [comment]
and also work with last commit of leaflet
