### ISSUE TITLE
Menu items don't work in IE (edge) and leaflet master

### ISSUE THREAD

**Issue by skalb** [aratcliffe/Leaflet.contextmenu#40]
Works chrome/firefox/safari.

In IE, the mousedown handler fires first and no item callbacks are called:

http://plnkr.co/edit/qgHsXjyrvCqNqXlUXTom?p=preview

**Comment by skalb** [comment]
Specifically, removing line https://github.com/aratcliffe/Leaflet.contextmenu/blob/master/src/Map.ContextMenu.js#L38 fixes the issue.

Is that handler needed for non-touch devices since the map mouseleave will close the menu anyway?

**Comment by chuduyunhuan** [comment]
in the environment of leaflet1.0 + IE11, the callback doesn't work, how can I solve this problem?

**Comment by aratcliffe** [comment]
This should be resolved now.
