### ISSUE TITLE
Feature Request: Tiered Menu

### ISSUE THREAD

**Issue by ahalota** [aratcliffe/Leaflet.contextmenu#41]
Tiered menu, either by simple indentation within the menu, or as a sub-menu.

**Comment by aratcliffe** [comment]
No plans to support this.

**Comment by Natureshadow** [comment]
I would actually like to implement this. Can I overtake this issue?

**Comment by aratcliffe** [comment]
Hi, your welcome to create a pull request for this feature if you implement. I haven't added it so far as I would have approached the design of the context menu differently if I was setting out to create a context menu that supported child menus. For example the menu class currently is currently associated with the owning map which is not applicable to child menus. A tiered menu should separate the menu UI code from the code related to map interaction. I would also consider implementing menu items as a class, encapsulating additional logic relating to child menus.
I would prefer to maintain backwards-compatibility with the existing API. What are your thoughts on this?
