### ISSUE TITLE
Modify existing mixin menu

### ISSUE THREAD

**Issue by aldensc** [aratcliffe/Leaflet.contextmenu#55]
I'm trying to modify an existing context menu that was bound to a polygon.  From what I read, it looks like access is always through the map's context menu.  When doing an operation like AddItem, how do I direct the add to the polygon's context menu and not the maps?

Sorry for posting this here, as it may not be an issue.  Probably my lack of understanding.

Thanks, Scott Alden (aldensc@ptd.net)

**Comment by aldensc** [comment]
I found that I can modify polygon.options.contextmenuItems[] directly and it takes affect.  I see where the map's context menu is loaded up with whichever context menu is being activated.  Makes sense.  Just not sure doing the direct modification of the array above is the correct thing to do.  Would be nicer to use the context menu methods for all modifications.  Please advise on the correct way to use this.  Thanks again.

**Comment by aratcliffe** [comment]
Hi Scott, sorry for the late reply. As you're probably aware the context menu mixin enables feature-specific menu items to be added to the map's context menu thus the context menu modification methods apply to the menu items shown for all features. It would be possible for the mixin to add methods to the feature for modification of it's menu items but as these methods don't currently exist there's no problem with modifying the array directly as you're doing.
