### ISSUE TITLE
Bower support?

### ISSUE THREAD

**Issue by deeg** [aratcliffe/Leaflet.contextmenu#56]
Any chance you would make a tag for known release version and put this into bower repository?

Looks like a nice library, would use!

**Comment by aratcliffe** [comment]
Hi, I'm not a bower user but there's already a bower.json file another user created so would I just need to create a tag and use "bower register" to release the library?

**Comment by deeg** [comment]
@aratcliffe, yes that is basically it. You should be able to follow the easy steps here: https://bower.io/docs/creating-packages/

**Comment by aratcliffe** [comment]
Done
