### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by flightsurvey** [aratcliffe/Leaflet.contextmenu#58]
We're soon to go into production and want to remove this console error:

leaflet.contextmenu.js:7 Uncaught TypeError: Cannot read property 'length' of undefined

Which occurs whenever the contextmenu is invoked with a right click. It doesn't seem to cause any problems in operation though.

**Comment by aratcliffe** [comment]
Which version of Leaflet are you using? Can you show me the context menu initialisation code?
