### ISSUE TITLE
Issues with Internet Explorer and leaflet1.0: Clicks in contextmenu registered as map clicks - nothing happens

### ISSUE THREAD

**Issue by AndreaAstronaut** [aratcliffe/Leaflet.contextmenu#59]
Hi there,

while using the leaflet.contextmenu with leaflet 0.7.x and internet explorer (version 11.545.10586.0) and Microsoft edge works perfect,
it does not register any menu selection when using leaflet1.0 instead. The contextmenu opens as normal but clicking a menu item gets registered as a click onto the map and therefore nothing happens.

I used the demo code (http://aratcliffe.github.io/Leaflet.contextmenu/examples/index.html) and just replaced the reference to the leaflet.js file to point to leaflet1.0.0.
I tried rc1 and rc3.

**Comment by aratcliffe** [comment]
Hi @AndreaAstronaut, thanks for letting me know. Did you test with Leaflet 1.0.0 under any other browsers? I haven't done any testing with Leaflet 1.0.0 myself.

**Comment by AndreaAstronaut** [comment]
Hi @aratcliffe,

thanks for your quick reply. It is working fine on chrome and firefox and opera. Did not test safari.

**Comment by aratcliffe** [comment]
Ok. I'll have a look over the next few days providing I can get a VM with IE 11 installed.

**Comment by romlebomba** [comment]
Are there any progress in getting this to work on IE11?

**Comment by Dr-Mx** [comment]
Tried it with Safari, works fine.  Still an issue with IE11 with the final release of Leaflet 1.0.0.

**Comment by aratcliffe** [comment]
Fixed in v1.0.1

**Comment by Dr-Mx** [comment]
Perfect, working as expected.  Thank you.

**Comment by fbonzon** [comment]
Can you update the version number in `package.json` and `bower.json`, and publish the package on https://www.npmjs.com/package/leaflet-contextmenu ?

The version number there is already v1.1.0. Maybe you'll be forced to increase it, i.e. v1.1.1 ?

**Comment by aratcliffe** [comment]
Yes the npm version is out of sync with the library releases. Doing a v1.1.1 release is probably the way to go. I believe the version property should be removed from bower.json as the git tags are used to determine available versions.

**Comment by fbonzon** [comment]
OK. Would be great you publish v1.1.1, so we can use this latest version with npm. Thanks
