### ISSUE TITLE
setDisabled(index, disabled)

### ISSUE THREAD

**Issue by flightsurvey** [aratcliffe/Leaflet.contextmenu#62]
I have created 5 contextmenu items for a marker which does not inherit the map menu and they behave as expected apart from not being able to be enabled.

They are assigned indexes in the following fashion and are initially disabled:

contextmenu: true,
contextmenuInheritItems: false,
contextmenuItems = [{
    text: editAddressText,
    callback: showEditAddress,
    icon: "../images/editaddress.png",
    disabled: true,
    index: 10
}, 
... etc

When they are conditionally enabled the following code executes without erroring but the items stay disabled:

for (i = 10; i < 15; i++) {
    map.contextmenu.setDisabled(i,false);
 }

Any ideas?

**Comment by aratcliffe** [comment]
Sorry for the late reply. Are you trying to enable the marker menu items when the context menu is not showing? The marker's menu items are recreated each time the menu is shown so you would need to conditionally enable the menu items when the menu is shown. You could try adding an event handler for the map's `contextmenu.show` event and do it in there.

**Comment by flightsurvey** [comment]
Thanks, I'll give it a go.
