### ISSUE TITLE
Extend ContextMenu

### ISSUE THREAD

**Issue by SkeDoodle** [aratcliffe/Leaflet.contextmenu#63]
Hi,

I'm trying to add nested menus to your awesome plugin.

Instead of changing the original code, I'm trying to extend it as follow:

`L.Map.ContextMenuExtender = L.Map.ContextMenu.extend({
})`

I would like to override certain methods such as `_showContextMenu` for instance. My idea, is that my overrided methods would be called instead of the original ones.

But I can't find a way of doing it.

Thanks in advance for the help.

Tom

**Comment by aratcliffe** [comment]
Hi Tom, nested menus is a feature that's requested from time to time but not something I've implemented with this plugin as it was written to meet the needs of a project which required only single-level menus. The plugin is designed around a single context menu instance which is associated with the map. Context menu items can be associated with map layers but the handler for the layer `contextmenu` event appends the layer's menu items to the map's context menu instance and shows that.

L.Map.ContextMenu is implemented as a map interaction handler which makes it unsuitable for association with an existing menu. For example when the menu is initialized `_createItems()`  is called which will create the menu's items from the configuration passed to the map constructor.

If you really need nested menus I'd suggest starting from scratch and implementing the context menu as a UI component independent from the context menu map handler.

**Comment by SkeDoodle** [comment]
Alright, thanks for the quick answer. If I have the time, I'll try fork your project and  try to implement it this way. For the time being, I'll put everything in a single-level menu with separators =).

Thank you again ! God I love open source =D.
