### ISSUE TITLE
Add support for retina icon

### ISSUE THREAD

**Issue by fbonzon** [aratcliffe/Leaflet.contextmenu#71]
The current `icon` option expects a 16×16 px image.

Similar to Leaflet core `iconUrl` and `iconRetinaUrl` options, it would be great to add a `retinaIcon` option in contextmenu, that accepts a 32×32 px image.

**Comment by aratcliffe** [comment]
Yes that's a great idea. I'll try and add it in later this evening.

**Comment by aratcliffe** [comment]
I've added this now. Sorry for the delay.

**Comment by fbonzon** [comment]
Awesome. You forgot to rebuild dist files in version 1.2.0. See #80

**Comment by aratcliffe** [comment]
Thanks François. Should be all good now :)

**Comment by fbonzon** [comment]
Verified, works as expected in version 1.2.1. Closing issue.
