### ISSUE TITLE
Chrome 55.0.2883.87 m

### ISSUE THREAD

**Issue by bocall** [aratcliffe/Leaflet.contextmenu#78]
Anyone having problems with contextmenu and Chrome 55.0.2883.87 m.  Menu worked on Chrome 54.0.2840.99 m but after updating Chrome the menu opens but clicks on the menu are not registered and the code does not get called.

Not sure if this is an issue or not.  But we have experienced this on 3 different devices after updating Chrome.

**Comment by aratcliffe** [comment]
Hi, I've updated to Chrome  55.0.2883.95 (Mac OSX) and the menu is working correctly for me.  Do you experience the problem with the demo? http://aratcliffe.github.io/Leaflet.contextmenu/examples/index.html

**Comment by bocall** [comment]
Hi, thanks for taking a look and getting back to me so soon.  Looks like it must be an issue I introduced in my own code as your demo works on the same device I am having the issue with.  I never thought to try that first, sorry.

**Comment by aratcliffe** [comment]
All good :)

**Comment by bocall** [comment]
Thanks.  I re-looked at my code and your example again and pulled down fresh copies of the files and it is working for me in my own code now.  My apologies again.  Thanks
