### ISSUE TITLE
Enable contextmenu only on marker and vector features?

### ISSUE THREAD

**Issue by Gendow** [aratcliffe/Leaflet.contextmenu#81]
Is it possible to add `callback`'s to marker and vector layer contextmenu's? I don't see this option in the documentation, but I did try to do it. 

Basically I want to get the layer after right clicking on a marker or vector layer so that I can pass it to `leaflet.draw`. I used the following approach and I got it partly working:

```
loadObjectGeometry: function(objectid) {

	var object = L.geoJSON(this.list, {
		style: styleObject,
		contextmenu: true,
		contextmenuItems: [{
			text: "Edit geometry",
			callback: editObject,
		}],
		onEachFeature: function(feature, layer){
			building.addLayer(layer)
		},
		filter: function(feature, layer) {
			if (feature.properties.dbk_id === objectid) {
				return true
			}
		}			
	})
	return object
}

function editObject(e) {
	var latlngs = e.relatedTarget.getLatLngs();
	var newPolygon = L.polygon(latlngs[0]);
       
        editableLayer.addLayer(newPolygon)
}
```
Note: I didn't set `contextmenu: true` when declaring my `map` (will come to this later)

This approach works: the menu shows up when right clicking on a layer. Clicking on one of the items in the menu returns a `e.relatedTarget` which enables me to do what ever I need to do with the layer.

However, I have the following issues:
* The contextmenu does not close when left-clicking anywhere outside the contextmenu
* multiple right-clicks on the map duplicates the items in the contextmenu with every click resulting in a huge contextmenu.

I tried to fix this issue by enabling the contextmenu when declaring the map with `contextmenu: true`. This solved the issues above. However, the click event does not return the `e.relatedTarget` anymore. In fact, it doesn't return any info considering the layer.

Why isn't there anything related to the layer returned when the `contextmenu` is set to true in the `map`? Is it possible to return to `e.relatedTarget`? It would be a nice option.

**Comment by Gendow** [comment]
I see that the approach to get the layer is to use the `contextmenu.show` event as mentioned in, for example, #32.

However I still have the issue of duplicating menu items and the menu not closing when left-clicking elsewhere on the map when the `contextmenu` is not enabled on the map. 

Any thoughts on this?

**Comment by zigstum** [comment]
I ran into the same problem with the duplicating items producing the longest menu in history, which I found a work around for. I added an icon class to the specific menu items I did not want duped, and before inserting the next menu items, I ran a small function that removes all items that have the icon class specified:
```function clearAddedTPItems(){
	var items = map.contextmenu._items;
	$.each(items, function( i, val ) {
		var firstKid = val.el.firstChild
		if(firstKid != null && $(firstKid).hasClass('fa-user')){
			$(val.el).remove();
		}
	});
}
No idea with the map not closing though.

**Comment by aratcliffe** [comment]
As per the docs the contextmenu mixin supports vector and marker layers only. Adding the menu configuration to a GeoJSON layer as you're doing will not work.

You need to use the GeoJSON layer's [onEachFeature](http://leafletjs.com/reference-1.0.2.html#geojson-oneachfeature) callback to bind the context menu to each feature. See https://github.com/aratcliffe/Leaflet.contextmenu/issues/39

**Comment by aratcliffe** [comment]
The map's contextmenu option should always set to `true` as the mixin extends the map's contextmenu with the layer menu items when the contextmenu is shown for the layer. Note you don't need to specify any menu items for the map if you want the contextmenu enabled for layers only.

**Comment by Gendow** [comment]
`onEachFeature` and setting map's contextMenu to `true` without adding menu items for the map fixed it.
