### ISSUE TITLE
Proposition: removeItem returns removed item to have possibility add removed item to context menu again.

### ISSUE THREAD

**Issue by cherniavskii** [aratcliffe/Leaflet.contextmenu#84]
Hej
It would be great, if `removeItem` method will return removed item (e.g. object, which was passed to `addItem` method). It will make possible to use this object again in `addItem` method.
I know, that there is possibility to keep object's reference after item was added to context menu, but I think that returning removed item will be more comfortable.
I'll try to implement this in a pull request, if you'll approve my proposition :)

**Comment by rheinheimer** [comment]
I second this. I am trying to manipulate a context menu item on click (specifically, change some styling in the menu item to reflect a toggled map item attribute), and I think the only way to do this is to remove the menu item then add a brand new item back in. It would certainly be more convenient if I could modify the menu item directly then add it back in.

Better still would be if we could manipulate the item's DOM element directly, without needing to remove it, but this is a different issue (unless cherniavskii's comment is to achieve the same thing- manipulation of the menu item).

**Comment by aratcliffe** [comment]
I've updated the `removeItem` and `removeAllItems` methods to return the removed menu item(s).

For styling changes you could either use the `addItem` method to add your menu item and retain a reference to the returned element OR use the `contextmenu.select` event.

**Comment by cherniavskii** [comment]
@aratcliffe thanks for your update!
But I meant a little bit different implementation.
Let's see a use case:
Context menu is dynamic and has different content depending on user's action. If we want to hide some item for a while, we should remove it from menu. And when we want to show this item back, we should add it back to menu. To avoid keeping reference to items, added on map init (in `contextmenuItems` array), it would be nice to make something like this: 
```
// remove item
var removedItem = map.contextmenu.removeItem(0);
// removeItem now is an options object, e.g. { text: "item", index: 0, callback: () => {...} }
......
......
// add it back
map.contextmenu.addItem(removedItem);
```
What do you think about this solution?

**Comment by aratcliffe** [comment]
By design menu items are plain HTML elements and once created the contextmenu no longer has reference to the options objects they were created from. Your app could hold a reference to the options objects and use addItem/removeItem methods to control the display of the individual menu items.

**Comment by cherniavskii** [comment]
Ok, thank's for response!
