### ISSUE TITLE
contextmenu.select event does not exist

### ISSUE THREAD

**Issue by rheinheimer** [aratcliffe/Leaflet.contextmenu#85]
I just wrote (and am now overwriting) a comment about `contextmenu.select` not working. It doesn't work because it is `contextmenu:select` (colon) in the script (which does work), and not `contextmenu.select` (dot) as in the readme.

So, the script or the readme should be revised.  Thanks!

**Comment by aratcliffe** [comment]
There was a typo in the source code. The event is `contextmenu.select`. This is fixed in the latest release. Thanks.
