### ISSUE TITLE
Illegal source tarball

### ISSUE THREAD

**Issue by Natureshadow** [aratcliffe/Leaflet.contextmenu#86]
Trying to package for Debian, I found that the source tarball is illegal. The MIT license requires the license text to be shipped with the source code.

Please add the license to the repository and make a new release, so distributions can package the software and users can use ti (right now, it is not legally possible for anyone to use the code).

**Comment by aratcliffe** [comment]
Hi, thanks for pointing this out. I've added the license file now.

**Comment by Natureshadow** [comment]
Thank you! The package will enter Debian sid shortly ☺.
