### ISSUE TITLE
Leaflet 1.1.0 incompatible

### ISSUE THREAD

**Issue by gonzaloplaza** [aratcliffe/Leaflet.contextmenu#95]
Some deprecations and errors found since recent upgrade to Leaflet 1.1.0, when you click on menu item. 

`Uncaught TypeError: Cannot read property 'off' of undefined`

```
L.DomEvent
                        .off(el, 'mouseover', this._onItemMouseOver, this)
                        .off(el, 'mouseover', this._onItemMouseOut, this)
                        .off(el, 'mousedown', L.DomEvent.stopPropagation)
                        .off(el, 'click', callback);
```

Are you planning to upgrade the contextmenu plugin to be compatible?. 

Thanks

**Comment by aratcliffe** [comment]
Hi, this is due to a bug in Leaflet 1.1.0 that has since been fixed: https://github.com/Leaflet/Leaflet/pull/5601

In the meantime you could downgrade or use Leaflet trunk.
