### ISSUE TITLE
Leaflet and LeafletContextmenu compatibility problem.

### ISSUE THREAD

**Issue by Stephlan** [aratcliffe/Leaflet.contextmenu#96]
Leaflet@1.1.0 is somehow not exactly compatible with leaflet.contextmenu@1.4.0
An error goes like:
 `Uncaught TypeError: Cannot read property 'off' of undefined <leaflet.contextmenu.js:281>`
while leaflet.contextmenu.js handling with right-click callback binding.
Plus to that, leaflet@1.0.3 supports correctly.

**Comment by aratcliffe** [comment]
This is a bug in Leaflet 1.1.0. See https://github.com/aratcliffe/Leaflet.contextmenu/issues/95

**Comment by Stephlan** [comment]
Oops, I missed that. Thanks and sorry for troubling!

**Comment by aratcliffe** [comment]
No worries. It will be fixed in the next Leaflet release.
