### ISSUE TITLE
Right click on popup

### ISSUE THREAD

**Issue by flightsurvey** [aratcliffe/Leaflet.contextmenu#98]
I have managed to disable the native browse popup on most dom elements in a leaflet application by issuing a series of jquery commands such as:

`  
$('.main-header').bind('contextmenu', function(e) {
      return false;
 });
`

But I am unable to find the class for a leaflet popup that will suppress the native browser action.

Any ideas?

**Comment by aratcliffe** [comment]
Sorry that's a question for the Leaflet developers.
